### ISSUE TITLE
Error on ruby 1.9.1

### ISSUE THREAD

**Issue by aleqi200** [guilhermechapiewski/correios-api#1]
ArgumentError: invalid byte sequence in UTF-8
    from /usr/lib/ruby/gems/1.9.1/gems/guilhermechapiewski-correios-api-0.1.2/lib/correios.rb:31:in `block in parse_tr'
    from /usr/lib/ruby/gems/1.9.1/gems/guilhermechapiewski-correios-api-0.1.2/lib/correios.rb:29:in`each'
    from /usr/lib/ruby/gems/1.9.1/gems/guilhermechapiewski-correios-api-0.1.2/lib/correios.rb:29:in `parse_tr'
    from /usr/lib/ruby/gems/1.9.1/gems/guilhermechapiewski-correios-api-0.1.2/lib/correios.rb:18:in`block in encomenda'
    from /usr/lib/ruby/gems/1.9.1/gems/guilhermechapiewski-correios-api-0.1.2/lib/correios.rb:16:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/guilhermechapiewski-correios-api-0.1.2/lib/correios.rb:16:in`encomenda'

**Comment by guilhermechapiewski** [comment]
Hey dude,

I'm not using this API for some time now and it might be broken in newer versions of Ruby.

Do you want to send me a patch to fix that? If you wish to do that, just remember to be backward compatible.

Thanks,
gc

**Comment by feromes** [comment]
Patched!
